---
- name: Cleanup PostgreSQL from all servers
  hosts: replica
  become: yes
  tasks:
    - name: Stop PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: stopped
      ignore_errors: true

    - name: Remove PostgreSQL packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      with_items:
        - postgresql
        - postgresql-client
        - postgresql-common
        - postgresql-contrib
        - libpq-dev

    - name: Remove PostgreSQL data directory
      ansible.builtin.file:
        path: "/var/lib/postgresql"
        state: absent

    - name: Remove PostgreSQL configuration directory
      ansible.builtin.file:
        path: "/etc/postgresql"
        state: absent

    - name: Remove PostgreSQL log directory
      ansible.builtin.file:
        path: "/var/log/postgresql"
        state: absent

    - name: Clean up PostgreSQL system files
      ansible.builtin.shell: |
        rm -rf /etc/apt/sources.list.d/pgdg.list
        rm -rf /usr/share/postgresql-common/pgdg
        rm -rf /usr/share/postgresql-common
        rm -rf /usr/lib/postgresql
        rm -rf /var/run/postgresql
      args:
        executable: /bin/bash
      ignore_errors: true

    - name: Ensure apt cache is cleaned
      ansible.builtin.apt:
        update_cache: yes
        autoclean: yes
        autoremove: yes
